apiVersion: v1
kind: PersistentVolume
metadata:
  name: sysbench
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: aksshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sysbench-premium
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret-premium
    shareName: akssharepremium
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
