apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysbench
  namespace: simple
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 512Gi