apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysbench
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sysbench
  template:
    metadata:
      labels:
        app: sysbench
    spec:
      containers:
      - image: htdp1/sysbench:latest
        name: sysbench
        command:
          - "sleep"
          - "604800"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        volumeMounts:
        - name: persistent-storage
          mountPath: /mnt/storage
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: sysbench
