apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysbench
  namespace: simple
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sysbench-premium
  namespace: simple
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 500Gi
